# config/security.yaml

security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            logout:
                path: security_logout
                target: security_login
            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator

    access_control:
        - { path: '^/my/account', roles: [ROLE_ADMIN, ROLE_USER] }

